name = "PauliCode"
uuid = "32bd6a1e-d0f4-4b31-8fff-2047310fcc76"
authors = ["keyang <chenkeyang@itp.ac.cn> and contributors"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
BenchmarkTools = "1.6.0"
Lazy = "0.15.1"
Oscar = "1.3.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
